import { DemoPreset } from '@/types/irrigation';

export const DEMO_PRESETS: DemoPreset[] = [
  {
    id: 'dry-wheat',
    name: '🌾 Dry Wheat Field',
    description: 'Severely depleted root-zone moisture during critical vegetative tillering stage with clear skies.',
    crop: 'wheat',
    growthStage: 'vegetative',
    soilType: 'loam',
    moisture: 28,
    temperature: 31,
    humidity: 42,
    rainProbability: 10,
    rainfallForecastMm: 0.0,
    daysSinceLastIrrigation: 6,
    expectedDecision: 'IRRIGATE',
    agronomicRationale:
      'Moisture (28%) has plummeted below the 40% threshold for tillering wheat. With only 10% rain probability and 31°C heat, evapotranspiration is rapid. High urgency irrigation is required to prevent yield-limiting tiller abortion.',
  },
  {
    id: 'rainy-rice',
    name: '🍚 Rainy Rice Field',
    description: 'Submerged paddy with impending high precipitation forecast.',
    crop: 'rice',
    growthStage: 'vegetative',
    soilType: 'clay',
    moisture: 75,
    temperature: 26,
    humidity: 88,
    rainProbability: 85,
    rainfallForecastMm: 34.0,
    daysSinceLastIrrigation: 2,
    expectedDecision: 'WAIT',
    agronomicRationale:
      'Rice at 75% moisture is at healthy target saturation. The forecast predicts an 85% probability of heavy rain (34 mm). Artificial irrigation would cause bund overflow, nutrient runoff, and wasteful pump energy. The agent correctly waits.',
  },
  {
    id: 'moderate-tomato',
    name: '🍅 Moderate Tomato Field',
    description: 'Borderline moisture with unsettled overcast sky during fruiting.',
    crop: 'tomato',
    growthStage: 'fruiting',
    soilType: 'loam',
    moisture: 48,
    temperature: 28,
    humidity: 62,
    rainProbability: 40,
    rainfallForecastMm: 4.5,
    daysSinceLastIrrigation: 3,
    expectedDecision: 'MONITOR',
    agronomicRationale:
      'Moisture (48%) is in the lower buffer of optimal (45-65%). With a 40% rain probability, premature irrigation risks calcium-leaching and fruit splitting if sudden downpours follow. Prudent agronomic practice is to MONITOR for 6-12 hours.',
  },
  {
    id: 'hot-cotton',
    name: '🌿 Hot Cotton Field',
    description: 'High heat wave during peak flowering stage with low rain probability.',
    crop: 'cotton',
    growthStage: 'flowering',
    soilType: 'clay',
    moisture: 35,
    temperature: 36,
    humidity: 35,
    rainProbability: 15,
    rainfallForecastMm: 0.0,
    daysSinceLastIrrigation: 5,
    expectedDecision: 'IRRIGATE',
    agronomicRationale:
      'Extreme heat (36°C) combined with flowering sensitivity. Square shedding occurs if moisture drops below 40% in flowering cotton. Despite clay retention, evaporation stress is critical. Precision irrigation required.',
  },
];
