import React from 'react';
import { AlertTriangle, ShieldCheck, Cpu } from 'lucide-react';

export function Footer() {
  return (
    <footer className="mt-auto border-t border-slate-900 bg-slate-950/90 py-8 px-4 sm:px-6 lg:px-8 text-xs text-slate-400">
      <div className="mx-auto max-w-7xl space-y-4">
        {/* Academic Prototype Disclaimer Alert */}
        <div className="flex items-start gap-2.5 rounded-lg border border-amber-500/30 bg-amber-950/20 p-3 text-amber-200/90">
          <AlertTriangle className="h-4 w-4 shrink-0 text-amber-400 mt-0.5" />
          <p className="leading-relaxed">
            <span className="font-semibold text-amber-300">Academic Prototype Notice:</span> Irrigation
            recommendations are generated by an academic AI prototype and should be validated against local
            agronomic conditions before real-world use. This system demonstrates multi-step agentic perception and
            reasoning for academic evaluation and does not constitute certified agricultural consultancy.
          </p>
        </div>

        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-2 border-t border-slate-900 text-slate-400">
          <div className="flex items-center gap-2">
            <Cpu className="h-4 w-4 text-emerald-400" />
            <span>Automated Irrigation Decision Agent • B.Tech Flexi Credit Project</span>
          </div>
          <div className="flex items-center gap-4 text-[11px]">
            <span className="flex items-center gap-1 text-emerald-400">
              <ShieldCheck className="h-3.5 w-3.5" /> Open-Meteo & Agronomic Physics
            </span>
            <span>Vercel AI SDK 7.0 • Next.js App Router</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
